### ISSUE TITLE
delharc sometimes gets wrong file names from Amiga archives

### ISSUE THREAD

**Issue by sonnenscheinchen** [royaltm/rust-delharc#1]
First off all thanks for delharc. It is very useful. :-)
Unfortunately there is an issue with some special case Amiga archives: If a comment a.k.a. "file note" is attached to a file, the `parse_pathname()` function doesn't stop parsing at the end of the file name but also includes the comment.

Small example archive attached.
Expected: `LhA.guide`
Currently returned: `LhA.guide%00Hello, I am a comment!`

Ah, and btw... Instead of fixing the bug it would be really cool to have file note support for delharc included, as we basically do have that already :-)
[comment.zip](https://github.com/royaltm/rust-delharc/files/6238015/comment.zip)

**Comment by royaltm** [comment]
Thanks for the report!

Looks like "the comment" is separated from the name by a C-string terminator.

My aim for delharc was to be as generic and as minimalistic as possible. Unfortunately the LHA/LZH format wasn't designed in a way to be easily extendable, so every tool and every operating system that uses it, somewhat abuses it by adding hacks to support whatever a special feature the OS was providing. Amiga file comments for example are very specific to Amiga.

That said it would be nice to support those custom hacks, but at the same time not to grow the library in a multiple of its current size.

I need to think a little bit how to extend delharc API to support such cases and also leave the current behavior mostly unchanged.

Perhaps you could inspire me with some ideas.

**Comment by royaltm** [comment]
https://github.com/royaltm/rust-delharc/commit/4781e9d74be9d8a0d930092beedf755b769d04db
I hope this helps.

Thanks for the comment.lha sample. I added it to regression tests.

**Comment by sonnenscheinchen** [comment]
Yes, this looks like a very good solution and is exactly what i needed. Thanks!

Issue can be closed, I guess...
