### ISSUE TITLE
Missing LICENSE or COPYING file

### ISSUE THREAD

**Issue by val-ms** [royaltm/rust-delharc#2]
The Cargo.toml file says the license is MIT.  But there is no LICENSE or COPYING file in the repository. 

Okay to add the MIT license file? 

Would you want to dual license under Apache 2.0 or MIT, in which case we should add 2 license files.

**Comment by royaltm** [comment]
I believe there is no need to include LICENSE file with the MIT license. This license is very simple.

**Comment by val-ms** [comment]
Generally a license file is required for any repo, notably for GitHub to recognize that it exists.  Some projects also choose to put the license information in file comments at the top of each source file, though I don't know of a functional reason.

**Comment by royaltm** [comment]
Please go ahead and make a pull request if you want to add the files. I changed the license in Cargo.toml to "MIT OR Apache-2.0".
